name: frontend_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  http: ^1.2.1
  intl: ^0.17.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
